version: '3.7'

services:

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  db:
    image: postgres
    volumes:
    - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: jetigenov
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    expose:
      - "5432"

  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8010
    volumes:
    - .:/code
    ports:
     - 80:80
    depends_on:
      - db